name: 'PR Difficulty Rating'
description: 'Provides a difficulty rating for PRs based on content diffs. Ratings are "Blue" (simple), "Red" (moderate), or "Black" (complex). The action adds a label and comment to the PR.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token for authentication'
    required: true
  LLAMA_URL:
    description: 'Llama.cpp API URL'
    required: true
  owner:
    description: 'Repository owner'
    required: false
  repo:
    description: 'Repository name'
    required: false
  pr_number:
    description: 'Pull request number'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - run: python ./main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        LLAMA_URL: ${{ inputs.LLAMA_URL }}
        OWNER: ${{ inputs.owner ?? github.repository_owner }}
        REPO: ${{ inputs.repo ?? github.repository.name }}
        pr_number: ${{ inputs.pr_number ?? github.event.pull_request.number }}
