name: 'PR Difficulty Rating'
description: 'Provides a difficulty rating for PRs based on content diffs. Ratings are "Blue" (simple), "Red" (moderate), or "Black" (complex). The action adds a label and comment to the PR.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token for authentication'
    required: true
  LLAMA_URL:
    description: 'Llama.cpp API URL'
    required: true
  OWNER:
    description: 'Repository owner'
    required: false
    default: ${{ github.repository_owner }}
  REPO:
    description: 'Repository name'
    required: false
    default: ${{ github.repository }}
  PR_NUMBER:
    description: 'Pull request number'
    required: false
    default: ${{ github.event.pull_request.number }}
runs:
  using: 'composite'
  steps:
    - name: Checkout action repo
      uses: actions/checkout@v2
      with:
        repository: rate-my-pr/gh-action
        ref: main
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - run: python main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        LLAMA_URL: ${{ inputs.LLAMA_URL }}
        OWNER: ${{ inputs.OWNER }}
        REPO: ${{ inputs.REPO }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
