name: Test PR Difficulty Rating Action

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  difficulty-rating:
    runs-on: ubuntu-latest
    steps:
      - uses: ./ # Uses an action in the root directory
        id: pr-difficulty-rating
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
