name: Test PR Difficulty Rating Action

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  difficulty-rating:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set Action Path
        id: set-action-path
        run: echo "::set-output name=action_path::./action.yml"

      - name: PR Difficulty Rating
        uses: ${{ steps.set-action-path.outputs.action_path }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
