name: Test PR Difficulty Rating Action

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  difficulty-rating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
        shell: bash
      - name: PR Difficulty Rating
        uses: rate-my-pr/gh-action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
