name: Test PR Difficulty Rating Action

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  difficulty-rating:
    runs-on: ubuntu-latest
    steps:
      - name: PR Difficulty Rating
        uses: rate-my-pr/gh-action@${{ github.event.pull_request.head.sha }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
